### ISSUE TITLE
Publishing 1.0.5 to hex

### ISSUE THREAD

**Issue by tsloughter** [knutin/elli#100]
I don't know if you published Elli to hex or not but we need to get 1.0.5 published.

Additionally, who ever did publish 1.0.4 had `rebar3_hex` in the plugins list of elli and not in the global list `~/.config/rebar3/rebar.config` which means any project that depends on elli ends up fetching that plugin for no reason. 

So if it was you who published, or if the person who did sees this :), it would be great to get 1.0.5 added and to not have `rebar3_hex` in the plugins list.

**Comment by knutin** [comment]
Oops. I'll get it sorted out on Monday. Thanks for letting me know.

**Comment by knutin** [comment]
Just published v1.0.5. Could you have a look if everything looks good?

**Comment by tsloughter** [comment]
Looks good, thanks!
