### ISSUE TITLE
Does elli support content-type is "application/json" for POST method?

### ISSUE THREAD

**Issue by wangyangkobe** [knutin/elli#103]
Hi, For Post method, the payload is json format, just like:

```
{  
   "UserId":"5",
   "Token":"b4f61c3e465847d481433d6c3ba086fb",
   "MacList":[  
      {  
         "Mac":"98:7B:F3:5A:61:70"
      }
   ]
}
```

So does elli support content-type is "application/json" for POST method?

**Comment by knutin** [comment]
Elli supports any content type and just gives you the body as a big binary.

If you want it to automatically be decoded, you can use a middleware to do it for you. There's one already for encoding the response (https://github.com/sthadka/elli_json) Maybe you can enhance it with a `preprocess` pass.
