### ISSUE TITLE
Why do elli depend on inets?

### ISSUE THREAD

**Issue by cvik** [knutin/elli#109]
Elli starts `inets` if you run `application:ensure_all_started(elli)`, yet `inets` isn't used anywhere.

**Comment by anha0825** [comment]
Hi, Elli uses ```http_uri:decode/1``` which is a part of ```inets```. ```http_uri:decode/1``` does not rely on the inets application being started so one could argue that it should be moved to ```included_applications```. Would that work for you?

**Comment by cvik** [comment]
True, didn't think to check for that. That solution absolutely works for me in the short run.

I just can't help the feeling that it is kind of dirty to pull in a library containing another full http-server, http-client and ftp-client, just to call the one function. Have you considered just copying that function into `elli` or write your own version? Would be happy to supply a PR if you want to outsource that. :)

**Comment by knutin** [comment]
Yeah, we'll happily take a PR for that :)
