### ISSUE TITLE
Large file uploads

### ISSUE THREAD

**Issue by mme** [knutin/elli#63]
Is it possible to handle large file uploads in middleware, i.e. stream the body to disk instead of keeping it in memory ?

**Comment by tsloughter** [comment]
Any chance of this being included? elli would be a nice successor to mochiweb and this seems like the main missing feature.

**Comment by rgrinberg** [comment]
Isn't this already included? Seems like handover functionality is in master https://github.com/knutin/elli/blob/master/src/elli_example_callback_handover.erl

**Comment by knutin** [comment]
Yup, it's been there a while even, just forgot to close this ticket. (:
